force-app/main/default/objects/Milestones__c/Milestones__c.object-meta.xml
<CustomObject>
    <label>Milestone</label>
    <nameField>
        <label>Milestones Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestones__c/fields/ProjectId__c.field-meta.xml
<CustomField>
    <fullName>ProjectId__c</fullName>
    <label>ProjectId</label>
    <referenceTo>Projects__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Milestones__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Start</fullName>
            </value>
            <value>
                <fullName>Middle</fullName>
            </value>
            <value>
                <fullName>Final</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MilestoneWrapper.cls
public with sharing class MilestoneWrapper {
  public Integer id { get; set; }
  public String name { get; set; }
  public String type { get; set; }
  public String dueDate { get; set; }
  public Boolean tasksCheckbox { get; set; }
  public List<TaskWrapper> tasks { get; set; }

  public Milestones__c getMilestone(String projectId) {
    Milestones__c mile = new Milestones__c();
    mile.Name = this.name;
    mile.ProjectId__c = projectId;
    mile.Type__c = this.type;
    mile.DueDate__c = Date.valueOf(this.dueDate);

    return mile;
  }

  public List<TaskWrapper> getTasks() {
    return this.tasks != null ? this.tasks : new List<TaskWrapper>();
  }
}