force-app/main/default/objects/Milestones__c/Milestones__c.object-meta.xml
<CustomObject>
    <label>Milestone</label>
    <nameField>
        <label>Milestones Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestones__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Milestones__c/fields/PercentCompleted__c.field-meta.xml
<CustomField>
    <fullName>PercentCompleted__c</fullName>
    <defaultValue>0</defaultValue>
    <label>% Completed</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Milestones__c/fields/ProjectId__c.field-meta.xml
<CustomField>
    <fullName>ProjectId__c</fullName>
    <label>ProjectId</label>
    <referenceTo>Projects__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Projects__c/Projects__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PO# {000}</displayFormat>
        <label>Projects Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Projects__c/fields/ProjectTitle__c.field-meta.xml
<CustomField>
    <fullName>ProjectTitle__c</fullName>
    <label>Project Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Projects__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GlobalStatusValue</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/GlobalStatusValue.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NotStarted</fullName>
        <default>true</default>
        <label>Not Started</label>
    </customValue>
    <customValue>
        <fullName>InProgress</fullName>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>Stopped</fullName>
    </customValue>
    <customValue>
        <fullName>Blocked</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <masterLabel>Global Status Value</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProjectControllerTest.cls
@isTest
public with sharing class ProjectControllerTest {
  @TestSetup
  static void makeData() {
    Projects__c project = new Projects__c();
    project.ProjectTitle__c = 'Test Project ';
    project.PercentCompleted__c = 0;

    insert project;

    List<Milestones__c> milestones = new List<Milestones__c>();
    for (Integer i = 1; i <= 2; i++) {
      milestones.add(
        new Milestones__c(
          Name = 'Milestone ' + i,
          ProjectId__c = project.Id,
          Status__c = i <= 2 ? 'Completed' : 'Not Started',
          IsActive__c = i > 2
        )
      );
    }

    insert milestones;

    List<Task> TasksList = new List<Task>();
    for (Integer i = 0; i < milestones.size(); i++) {
      for (Integer j = 1; j <= 4; j++) {
        TasksList.add(
          new Task(
            Subject = 'Task ' + j + ' - Milestone ' + (i + 1),
            WhatId = milestones[i].Id,
            Status = j <= 2 ? 'Completed' : 'Not Started'
          )
        );
      }
    }
    insert TasksList;
  }

  @isTest
  public static void getMilestonesWithTasksTest() {
    Projects__c project = [
      SELECT Id, ProjectTitle__c, PercentCompleted__c
      FROM Projects__c
    ];

    Test.startTest();
    List<ProjectController.ResponseWrapper> result = ProjectController.projectOverview(
      project.Id
    );
    Test.stopTest();

    System.assertNotEquals(null, result);
    System.assertEquals(2, result.size(), 'Should return 2 milestones');

    Boolean foundTasks = false;
    for (ProjectController.ResponseWrapper wrapper : result) {
      System.assertNotEquals(
        null,
        wrapper.milestone,
        'Milestone should not be null'
      );

      if (!wrapper.tasks.isEmpty()) {
        foundTasks = true;
      }
    }

    System.assertEquals(
      true,
      foundTasks,
      'At least one milestone should have tasks'
    );
  }
}